name: Generate Keybox

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'keyboxGenerator_v2.0.py'

jobs:
  generate-keybox:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openssl libssl-dev

    - name: Run keybox generator
      run: python generate_keybox.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: keybox-files
        path: |
          ecPrivateKey.pem
          certificate.pem
          rsaPrivateKey.pem
          keybox.xml
        if-no-files-found: warn
